"""Initial migration.

Revision ID: bf783d29f678
Revises: 9c3d523ecebe
Create Date: 2021-08-24 19:05:09.111694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf783d29f678'
down_revision = '9c3d523ecebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('backings_reward_id_fkey', 'backings', type_='foreignkey')
    op.drop_column('backings', 'reward_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backings', sa.Column('reward_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('backings_reward_id_fkey', 'backings', 'rewards', ['reward_id'], ['id'])
    # ### end Alembic commands ###
