"""Initial migration.

Revision ID: 9c3d523ecebe
Revises: 8cfbefa0054b
Create Date: 2021-08-24 19:00:44.371072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3d523ecebe'
down_revision = '8cfbefa0054b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backings', sa.Column('comment', sa.String(length=255), nullable=False))
    op.alter_column('projects', 'funding_raised',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'backers',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'backers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'funding_raised',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('backings', 'comment')
    # ### end Alembic commands ###
