"""Initial migration

Revision ID: dd6861d43f2e
Revises: 3c18eba0d4b4
Create Date: 2021-08-23 23:15:05.212190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6861d43f2e'
down_revision = '3c18eba0d4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'backings', 'rewards', ['reward_id'], ['id'])
    op.create_foreign_key(None, 'backings', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'backings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'rewards', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rewards', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'backings', type_='foreignkey')
    op.drop_constraint(None, 'backings', type_='foreignkey')
    op.drop_constraint(None, 'backings', type_='foreignkey')
    # ### end Alembic commands ###
