"""Initial migration.

Revision ID: bbfd32ef1986
Revises: ef33b4dd06a7
Create Date: 2021-08-25 17:21:58.921569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbfd32ef1986'
down_revision = 'ef33b4dd06a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewards', 'details2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('details2', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
