"""Initial migration.

Revision ID: ef33b4dd06a7
Revises: 
Create Date: 2021-08-25 17:21:35.653643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef33b4dd06a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('details2', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewards', 'details2')
    # ### end Alembic commands ###
